In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import numpy as np

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor

In [4]:
from sklearn.metrics import  r2_score

In [5]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
data =pd.read_csv("Excercise4.csv")
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [8]:
print ("Before rows remvoal ->", len(data))
data.drop_duplicates(keep ="first")
print ("After duplicate removal ->", len(data))

Before rows remvoal -> 8523
After duplicate removal -> 8523

In [9]:
data.isna().sum()
data[data.isna().any(axis=1)==True]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.20,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.20,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350
18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
...,...,...,...,...,...,...,...,...,...,...,...,...
8504,NCN18,NaN,Low Fat,0.124111,Household,111.7544,OUT027,1985,Medium,Tier 3,Supermarket Type3,4138.6128
8508,FDW31,11.35,Regular,0.043246,Fruits and Vegetables,199.4742,OUT045,2002,NaN,Tier 2,Supermarket Type1,2587.9646
8509,FDG45,8.10,Low Fat,0.214306,Fruits and Vegetables,213.9902,OUT010,1998,NaN,Tier 3,Grocery Store,424.7804
8514,FDA01,15.00,Regular,0.054489,Canned,57.5904,OUT045,2002,NaN,Tier 2,Supermarket Type1,468.7232
8519,FDS36,8.38,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [11]:
def missing_data_threshold(data, Threshold = 75 ):
    missing_data = pd.DataFrame(data.isna().sum(), columns= ["missing_count"])
    missing_data["missing_percentage"] = missing_data["missing_count"]/len(data)
    columns_to_be_deleted = missing_data[missing_data["missing_percentage"]>= Threshold].index
    print("Deleted columns due to missing values> Threshold are-->",
          list(columns_to_be_deleted))
    data= data.drop(columns= columns_to_be_deleted)
    return data

In [12]:
data = missing_data_threshold(data, Threshold=75)
data.head()

Deleted columns due to missing values> Threshold are--> []

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [13]:
data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

##check whether to use mean or median for filling blank values

In [14]:
data['Item_Weight'].describe()

count    7060.000000
mean       12.857645
std         4.643456
min         4.555000
25%         8.773750
50%        12.600000
75%        16.850000
max        21.350000
Name: Item_Weight, dtype: float64

In [15]:

#since mean and median are very close use  "mean"

In [16]:
data['Outlet_Size'].describe()

count       6113
unique         3
top       Medium
freq        2793
Name: Outlet_Size, dtype: object

In [17]:
#use mode

In [18]:
data["Item_Weight"].mean()

np.float64(12.857645184135976)

In [19]:
data['Outlet_Size'].fillna(data['Outlet_Size'].mode())

0       Medium
1       Medium
2       Medium
3          NaN
4         High
         ...
8518      High
8519       NaN
8520     Small
8521    Medium
8522     Small
Name: Outlet_Size, Length: 8523, dtype: object

In [20]:
data['Outlet_Size'].isnull().sum()

np.int64(2410)

In [21]:
def missing_data_treatment(data):
   '''Treat missing values using median and mode'''
   for  col in data.columns:
      if data[col].dtype =='object':
        mode_value = data[col].mode()[0]
        print(col, "-->", data[col].dtype, "-->", mode_value)
        data[col] = data[col].fillna(mode_value)
      else:
        median_value = data[col].median()
        print(col, "-->", data[col].dtype, "-->", median_value)
        data[col] = data[col].fillna(median_value)
   return data

In [22]:
data = missing_data_treatment(data)

Item_Identifier --> object --> FDG33
Item_Weight --> float64 --> 12.6
Item_Fat_Content --> object --> Low Fat
Item_Visibility --> float64 --> 0.053930934
Item_Type --> object --> Fruits and Vegetables
Item_MRP --> float64 --> 143.0128
Outlet_Identifier --> object --> OUT027
Outlet_Establishment_Year --> int64 --> 1999.0
Outlet_Size --> object --> Medium
Outlet_Location_Type --> object --> Tier 3
Outlet_Type --> object --> Supermarket Type1
Item_Outlet_Sales --> float64 --> 1794.331

In [23]:
data.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [24]:
data.nunique()

Item_Identifier              1559
Item_Weight                   415
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     3
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                8523 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [26]:
def feature_engineering(data):
    ''' Reduce variety of columns having more than 5% variety using bins'''
    for col in data.columns:
      if 100*data[col].nunique()/len(data)>5:
        if  data[col].dtype=='object':
            print('Skip --> manually reduce variety for', col)
        else:
            new_col_name=col + '_bucket'
            data[new_col_name] = pd.qcut(data[col], 4, labels=['b1','b2','b3', 'b4'])
            print('Auto reduced variety for', col)
    return data
data = feature_engineering(data)

Skip --> manually reduce variety for Item_Identifier
Auto reduced variety for Item_Visibility
Auto reduced variety for Item_MRP
Auto reduced variety for Item_Outlet_Sales

label Encoding

In [27]:
sorted(data['Item_Fat_Content'].unique())

['LF', 'Low Fat', 'Regular', 'low fat', 'reg']

In [28]:
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({
    'LF': 'Low Fat',
    'low fat': 'Low Fat',
    'reg': 'Regular'
})

In [29]:
sorted(data['Item_Fat_Content'].unique())

['Low Fat', 'Regular']

In [30]:
LN = LabelEncoder()
data['Item_Fat_Content'] = LN.fit_transform(data['Item_Fat_Content'])
sorted(data['Item_Fat_Content'].unique())

[np.int64(0), np.int64(1)]

In [31]:
sorted(data['Item_Type'].unique())

['Baking Goods',
 'Breads',
 'Breakfast',
 'Canned',
 'Dairy',
 'Frozen Foods',
 'Fruits and Vegetables',
 'Hard Drinks',
 'Health and Hygiene',
 'Household',
 'Meat',
 'Others',
 'Seafood',
 'Snack Foods',
 'Soft Drinks',
 'Starchy Foods']

In [32]:
def label_encoding(data):
    '''Convert all alphabetical column to numeric column'''
    LN = LabelEncoder()
    for col in data.columns:
        if (data[col].dtype=='object') or (data[col].dtype == 'category'):
            print(col)
            print('before -->', data[col].unique())
            data[col] = LN.fit_transform(data[col])
            print('After -->', data[col].unique())
            print('-'*80)
    return data

In [33]:
data= label_encoding(data)

Item_Identifier
before --> ['FDA15' 'DRC01' 'FDN15' ... 'NCF55' 'NCW30' 'NCW05']
After --> [ 156    8  662 ... 1323 1524 1519]
--------------------------------------------------------------------------------
Item_Type
before --> ['Dairy' 'Soft Drinks' 'Meat' 'Fruits and Vegetables' 'Household'
 'Baking Goods' 'Snack Foods' 'Frozen Foods' 'Breakfast'
 'Health and Hygiene' 'Hard Drinks' 'Canned' 'Breads' 'Starchy Foods'
 'Others' 'Seafood']
After --> [ 4 14 10  6  9  0 13  5  2  8  7  3  1 15 11 12]
--------------------------------------------------------------------------------
Outlet_Identifier
before --> ['OUT049' 'OUT018' 'OUT010' 'OUT013' 'OUT027' 'OUT045' 'OUT017' 'OUT046'
 'OUT035' 'OUT019']
After --> [9 3 0 1 5 7 2 8 6 4]
--------------------------------------------------------------------------------
Outlet_Size
before --> ['Medium' 'High' 'Small']
After --> [1 0 2]
--------------------------------------------------------------------------------
Outlet_Location_Type
before --> ['Tier 1' 'Tier 3' 'Tier 2']
After --> [0 2 1]
--------------------------------------------------------------------------------
Outlet_Type
before --> ['Supermarket Type1' 'Supermarket Type2' 'Grocery Store'
 'Supermarket Type3']
After --> [1 2 0 3]
--------------------------------------------------------------------------------
Item_Visibility_bucket
before --> ['b1', 'b4', 'b3', 'b2']
Categories (4, object): ['b1' < 'b2' < 'b3' < 'b4']
After --> [0 3 2 1]
--------------------------------------------------------------------------------
Item_MRP_bucket
before --> ['b4', 'b1', 'b2', 'b3']
Categories (4, object): ['b1' < 'b2' < 'b3' < 'b4']
After --> [3 0 1 2]
--------------------------------------------------------------------------------
Item_Outlet_Sales_bucket
before --> ['b4', 'b1', 'b3', 'b2']
Categories (4, object): ['b1' < 'b2' < 'b3' < 'b4']
After --> [3 0 2 1]
--------------------------------------------------------------------------------

correlation

In [34]:
corr=100*data.corr()
corr.style.background_gradient(cmap ='coolwarm')

In [35]:
data = data.drop(columns= ['Item_MRP_bucket'])
data.head(2)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_Visibility_bucket,Item_Outlet_Sales_bucket
0,156,9.30,0,0.016047,4,249.8092,9,1999,1,0,1,3735.1380,0,3
1,8,5.92,1,0.019278,14,48.2692,3,2009,1,2,2,443.4228,0,0

In [36]:
corr= 100*data.corr()
corr.style.background_gradient(cmap ='coolwarm')

In [37]:
y = data['Item_Outlet_Sales']
x= data.drop(columns= ['Item_Outlet_Sales'])

In [38]:
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size=0.7,random_state=1234)

In [39]:
len(x_test)

2557

model development

In [40]:
model = LinearRegression()
model = model.fit(x_train, y_train)

In [41]:
y_pred = model.predict(x_test)
y_pred

array([  32.94622339, 2669.06439229, 4335.47417126, ..., 2039.25773503,
       4221.94887823, -102.03346772])

In [42]:
accuracy = 100*r2_score(y_test, y_pred)
accuracy

81.24960571309764

In [43]:
models=[LinearRegression(),Lasso(),Ridge(),ElasticNet(),
        DecisionTreeRegressor(),RandomForestRegressor(),
        BaggingRegressor(),AdaBoostRegressor(),KNeighborsRegressor()]

In [44]:
for model in models:
    model=model
    model=model.fit(x_train,y_train)
    y_pred= model.predict(x_test)
    accuracy = 100*r2_score(y_test,y_pred)

    print(model,'-->', accuracy)

LinearRegression() --> 81.24960571309764
Lasso() --> 81.25208421441768
Ridge() --> 81.25156379308073
ElasticNet() --> 75.32482347316875
DecisionTreeRegressor() --> 72.02124454822491
RandomForestRegressor() --> 85.7346959723943
BaggingRegressor() --> 84.72148504904166
AdaBoostRegressor() --> 84.2401818846499
KNeighborsRegressor() --> 22.23423472141668